version: 2.1

jobs:
  build-and-test:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout

      - run:
          name: Login to DockerHub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin

      - run:
          name: Build Docker Image
          command: docker build -t sample-app .

      - run:
          name: Run and Test Docker Container
          command: |
            docker run -d -p 8080:8080 --name sample-app-container sample-app
            sleep 2
            curl -f http://localhost:8080 || (echo "L'application n'a pas démarré correctement"; exit 1)

      - run:
          name: Push Docker Image to DockerHub
          command: |
            docker tag sample-app $DOCKERHUB_USER/sample-app:latest
            docker push $DOCKERHUB_USER/sample-app:latest

workflows:
  version: 2
  build-test-push:
    jobs:
      - build-and-test
