version: 2.1

orbs:
  docker: circleci/docker@2.8.1

jobs:
  build-and-test:

    machine:
      image: ubuntu-2204:2023.10.1

    steps:

      - checkout

      - run:
          name: Install curl
          command: sudo apt-get update && sudo apt-get install -y curl


      - docker/build:
          image: sample-app

      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8080:8080 --name sample-app-container sample-app
            sleep 2

      - run:
          name: Test App
          command: curl -f http://127.0.0.1:8080 || (echo "App is not responding"; exit 1)

      - docker/publish:
          image: sample-app
          tag: $DOCKERHUB_USER/sample-app:latest
          registry: https://index.docker.io/v1/
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS

workflows:
  version: 2
  build-test-push:
    jobs:
      - build-and-test
