version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202101-01
    steps:

      - checkout

      - run:
          name: Install curl
          command: sudo apt-get update && sudo apt-get install -y curl

      - run:
          name: Login to DockerHub
          command: echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin

      - run:
          name: Build Docker Image
          command: docker build -t sample-app .

      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8080:8080 --name sample-app-container sample-app
            sleep 2

      - run:
          name: Test App
          command: curl -f http://127.0.0.1:8080 || (echo "App is not responding"; exit 1)

      - run:
          name: Push Docker Image to DockerHub
          command: |
            docker tag sample-app $DOCKERHUB_USER/sample-app:latest
            docker push $DOCKERHUB_USER/sample-app:latest

workflows:
  version: 2
  build-test-push:
    jobs:
      - build-and-test
